[package]
name = "skreate-docgen"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
handlebars = "6"
serde_json = "1.0.39"
skreate = "*"
urlencoding = "2.1"
